### ISSUE TITLE
Headers/Footers

### ISSUE THREAD

**Issue by pottedmeat** [dojo/dgrid#11]
**Enhancement** 

In dgrid 1, the header is fully managed by the widget itself, while the footer is customizable - used by the pagination mixin and for user-provided content like summary rows (http://dgrid.io/tutorials/1.0/summary_row/).

Users have requested customization of the header in the same way (https://github.com/SitePen/dgrid/issues/211) as the footer. Making both areas behave similarly is something we should pursue in dgrid 2.

Both the header and the footer should operate both with fixed positioning as is the case with pagination or locked to the horizontal scrolling of the grid - or column sets that scroll independently - as is the case with summary rows and headers.

## Questions

* Should there be "more than 1" header or footer such as having both pagination and a summary row?
* Should these be configurable?
* Should we have bundled into the grid all header variations, pagination widgets, and summary widgets?
* If we do allow for configuration, how are these passed to the grid?
* What would keeping horizontal scrolling in sync look like?

**Comment by dylans** [comment]
> Should there be "more than 1" header or footer such as having both pagination and a summary row?

If history is an indicator of the things people want to do, yes. The question is, should this be things that dgrid does, or something another related widget should do that is documented for usage with dgrid? In other words, we don't have to bake everything into dgrid necessarily, just need to make sure that things are well documented and easy to use together to get the features we want.

> Should these be configurable?

That's pretty open-ended. I mean, everything is configurable, but what did you have in mind here. :)

> Should we have bundled into the grid all header variations, pagination widgets, and summary widgets?

Let's perhaps determine what bundled means. Does that mean a separate widget within the dgrid package? Are these widgets only to be used with dgrid (e.g. do they make a lot of dgrid-based assumptions about their usage)?

> If we do allow for configuration, how are these passed to the grid?

How does configuration differ from properties? I don't know the right patterns or vocabulary for how smaller sets of widgets get aggregated into a bigger widget, but I assume it's some sort of container widget that manages the relationship with its children?

> What would keeping horizontal scrolling in sync look like?

It would look like it's in sync. ;) More seriously, I don't know the right pattern, but I assume some sort of scroll event would get passed to the container which would update the header/footer layout unless we can rely on native scrolling which I assume we cannot.

cc @ant @matt-gadd for their thoughts.

**Comment by msssk** [comment]
> Should there be "more than 1" header or footer such as having both pagination and a summary row?

Yes. Common customizations include adding rows above or below, but mostly visually integrated with, the header row. The footer should also accommodate multiple custom rows.

Another modification that should be achievable is adding content within the header cells. For example, a filtering UI may want to add filter fields immediately below the column title text - if these fields are in a different row it creates an undesirable visual effect when cells in one of the rows are hovered.

> Should these be configurable?

Yes.

> Should we have bundled into the grid all header variations, pagination widgets, and summary widgets?

No, but we need to ensure our architecture is extensible:

* flexible DOM structure manipulation
* robust event manipulation (e.g. cancel or modify sort event)

**Comment by dylans** [comment]
Given that #18 and #25 have landed, is this being left open for more advanced versions, or should this be considered done @pottedmeat ?

**Comment by pottedmeat** [comment]
Yeah, we have yet to check in the pagination integration, which should give us a good method of figuring out/testing the final implementation.
