### ISSUE TITLE
Sizing

### ISSUE THREAD

**Issue by pottedmeat** [dojo/dgrid#13]
**Enhancement** 

The goal of dgrid sizing is to allow the user to specify an overall height for the grid from which the scrollable area is that height minus the header and footer areas.

In dgrid, there is a locked (non-scrolling) header area, a locked footer area, and scrolling content within which the scrollbar should start below the header and above the footer.

With normal CSS, the only way to make an area scroll is to give the parent an explicit size. The only way to give the parent an explicit size is to set it manually - either by setting a height or absolutely positioning it within a parent with an explicit size using top/right/bottom/left values.

With a header and footer, this means something has to set the height/absolute positions of the scrollable parent manually - which is what's currently done - but requires manually reading the size of the header and footer and listening for resize events to re-read these values.

Because of this, it looks like the best option is to use flex box, at least for this part of the grid. Linked is a simple demo showing how this approach would work: https://jsfiddle.net/a72nu1vw/2/

**Comment by msssk** [comment]
How do we achieve a fixed grid height regardless of content? In the linked fiddle if you remove a lot of the text in the scroller the entire grid height shrinks, moving the footer up.

**Comment by pottedmeat** [comment]
Valid point - Updated so that `.scroller` has `flex-grow: 1;` https://jsfiddle.net/a72nu1vw/2/
