### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by pottedmeat** [dojo/dgrid#22]
**Enhancement** 

## Data Provider

We need to add information to the [Data Metadata](https://github.com/dojo/dgrid/issues/4) to limit the bounds of on demand scrolling where the most appropriate location is probably the `size` property bag.

* `start`
* `totalLength`
* `min`: new - the lowest index that can be part of a slice (inclusive)
* `max`: new - the highest index that can be part of a slice (inclusive)

## Pagination Widget

The Pagination widget will manage very little on its own - it will accept properties and callbacks that generically display a pagination UI.

* `status: string;` - A status message to show, generally indicating what's on that page
* `page: number;` - The page that should be marked as selected
* `pages: number;` - The total number of pages
* `onPageRequest(page: number): void;`

To increase/decrease the page, the onPageRequest listener will have to be implemented and will have to update the properties being passed to the Pagination widget with the new number;

## GridPagination Widget

This wraps any widget (passed as a string/constructor in its properties) that conforms to the basic interface of the Pagination Widget. It also accepts a data provider as one of its properties but expects the data provider to have a `slicePage` method and to return data with `size.min`/`size.max`.

When `data` is updated (observed), `data.size.min` is used to grab the page number which it uses to pass to its child pagination widget.

## Populating Data

The `GridPagination` widget will make a call to `onPageRequest` when its `page` or `itemsPerPage` properties change. This will in turn set `data.size.min` and `data.size.max` which will ensure the `onSliceRequest` call made in `Body` is either identical (if all rows are displayed) or contains a subset of data just from that page.

## Becoming Part of dgrid

A `DNode` (`w` call) version of this widget will be passed to the grid in the `footers` property.

## Adding `slicePage` and `size.min`/`size.max` to a Data Provider

A class mixin for `DataProvider` will add the `slicePage` method and override `updateData` from `BaseDataProvider` to set the new data properties.

In this base mixin, `slicePage` is a wrapper for `slice` which also adds additional state properties, `page` and `itemsPerPage`.

## Setting `itemsPerPage`

So far, the grid doesn't know anything about paging. But `itemsPerPage` needs to be set somewhere. It can be one of the properties of `GridPagination` where that widget then communicates that value to the passed data provider (e.g. as part of a `slicePage(page: number, itemsPerPage: number)` method call).

It should also allow for a specific page to be chosen using `setProperties` with the page variable and receiving a callback to ensure it isn't reset next call.

## `items.length !== pagination.itemsPerPage`

It is likely the data provider will want to provide a number of rows not equal to the number of items per page. This should be allowed.

An example of this would be when a tree is used alongside pagination. To provide context, the grid may want to provide each parent as the items that are a part of that page. 

## Paging UI

* Left side: "1 - 10 of 50 results"
* Right side: prev, next, and page numbers
* Prev is grayed out if on the first page
* Next is grayed out if on the last page
* Current page is grayed out
* To the left of the current page are the 2 previous page numbers (when possible)
* To the right of the current page are the 2 next page numbers (when possible)
* The first item in pagination is always page 1
* The last item in pagination is always the last page number (unless a single page)
* Any numbers not covered by these rules are removed and ellipses are added in their place
* Any numbers not grayed out are clickable

**Comment by pottedmeat** [comment]
Updated based on feedback from the widget patterns meeting.

**Comment by msssk** [comment]
We should probably also include the option to have first (‹‹) and last (››) links.

**Comment by pottedmeat** [comment]
Added a section on populating data.
