### ISSUE TITLE
Is this still maintained? Can I use sitepen/dgrid with dojo2 ?

### ISSUE THREAD

**Issue by asyncmind0** [dojo/dgrid#51]
**Bug / Enhancement** 

Package Version: 

**Code**

**Expected behavior:**

**Actual behavior:**

**Comment by dylans** [comment]
Yes, but most of the focus is on newer Dojo and an eventual dgrid replacement. It is possible to use dgrid with Dojo 2+ but it is not straightforward and does not support all features.

**Comment by ILoveITScience** [comment]
@dylans would you please provide a link to the new data grid.

**Comment by yduman** [comment]
What's the current status of the "dgrid replacement"? I'm trying to realize a data table with CRUD operations and I'm currently looking what's available from Dojo. Is dgrid the only option to realize this, or are there other sources I can look into?

**Comment by agubler** [comment]
@yduman If you need a grid in dojo 2+ there is a basic grid in [`dojo/widgets`](https://github.com/dojo/widgets/tree/master/src/grid), which you should be able to use to render data from a REST API. Additionally we have also added support for using dgrid in dojo2 with the `DgridWrapper` in [`dojo/interop`](https://github.com/dojo/interop#dgridwrapper).
